### ISSUE TITLE
Dist should not be version controlled

### ISSUE THREAD

**Issue by yangshun** [li-kai/modify#2]
The `dist` folder should be `gitignore`-ed if possible. You can actually use this to deploy a `dist` folder to `gh-pages`. More info here: http://survivejs.com/webpack/building-with-webpack/hosting-on-github-pages/

**Comment by li-kai** [comment]
You're right, I shouldn't be tracking it. I just didn't know alternatives and chose the easy way. I fixed it, thanks!
