### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by sfdye** [li-kai/modify#6]
https://www.modify.sg/ seems down.

I am from NTU and I am willing to contribute if this project is still on.

**Comment by li-kai** [comment]
@sfdye Unfortunately no, I have since focused efforts at [nusmods](https://github.com/nusmodifications/nusmods). And I hope to bring our contributions over there to ntu as well. We'll be glad if you're willing to help us out 😄

**Comment by sfdye** [comment]
I see. `nusmod` is pretty awesome! Actually I did a same thing ntusanta.com when I was in school but now not maintaining the project it anymore.

Would be happy to help. Let me how I can "fork" `nusmode` to ntu?
